### ISSUE TITLE
I'm very confused with ROI pooling's result.

### ISSUE THREAD

**Issue by asdfghwunai** [deepsense-ai/roi-pooling#14]
Hi,thank you for your great work.I have a problem.
If
input_value = [[
    [[1], [2], [4], [4],[5],[6]],
    [[3], [4], [1], [12],[5],[6]],
    [[6], [2], [1], [7.0],[5],[6]],
    [[1], [0], [2], [8],[5],[6]]
]]

rois_value = [
    [0, 0, 0, 3, 5]     #4*6
]

y = roi_pooling(input, rois, pool_height=2, pool_width=2)

then,the output is
y:  [[[[  6.  12.]
   [  1.   8.]]]]

I think a sub-window’s size is 2*3,so the result should be 
 [[[[  4.  12.]
   [  6.   8.]]]]
So can you tell me how your code works?Thank you.

**Comment by tgrel** [comment]
My first guess is that the ROI size in this case is 3x5 not 4x6 as indicated by your comment. Please see my blog post explaining the operation in details here: https://blog.deepsense.ai/region-of-interest-pooling-explained/

I'm closing the issue since it's more suitable for a StackOverflow question than a Github issue.
